pipeline {

  options {
    ansiColor('xterm')
  }

  agent {
    kubernetes {
      yamlFile 'builder.yaml'
    }
  }

  stages {

    stage('Kaniko Build & Push "cartservice" Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/src/cartservice/src/Dockerfile \
                             --context `pwd`/src/cartservice/src/ \
                             --destination=marinyuk/cartservice:${BUILD_NUMBER} \
                             --destination=marinyuk/cartservice:latest
            '''
          }
        }
      }
    }

    stage('Deploy "cartservice" App to Kubernetes') {     
      steps {
        container('kubectl') {
          withCredentials([file(credentialsId: 'mykubeconfig', variable: 'KUBECONFIG')]) {
            sh 'sed -i "s/latest/${BUILD_NUMBER}/" src/cartservice/yaml/deployment.yaml'
            sh 'cat src/cartservice/yaml/deployment.yaml'
            sh 'kubectl apply -f src/cartservice/yaml/deployment.yaml -n microservices'
          }
        }
      }
    }
  
  }
}
