pipeline {

  options {
    ansiColor('xterm')
  }

  agent {
    kubernetes {
      yamlFile 'builder.yaml'
    }
  }

  stages {

    stage('Kaniko Build & Push "loadgenerator" Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/src/loadgenerator/Dockerfile \
                             --context `pwd`/src/loadgenerator/ \
                             --destination=marinyuk/loadgenerator:${BUILD_NUMBER} \
                             --destination=marinyuk/loadgenerator:latest
            '''
          }
        }
      }
    }

    stage('Deploy "loadgenerator" App to Kubernetes') {     
      steps {
        container('kubectl') {
          withCredentials([file(credentialsId: 'mykubeconfig', variable: 'KUBECONFIG')]) {
            sh 'kubectl apply -f src/loadgenerator/yaml/deployment.yaml -n microservices'
          }
        }
      }
    }
  
  }
}