---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shop.medevelop.studio-cert
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
  secretName: shop.medevelop.studio-secret
  commonName: shop.medevelop.studio
  dnsNames:
  - shop.medevelop.studio

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-shop-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
#  - port:
#      number: 80
#      name: http
#      protocol: HTTP
#    tls:
#      httpsRedirect: true
#    hosts:
#    - "shop.medevelop.studio"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: shop.medevelop.studio-secret
    hosts:
    - shop.medevelop.studio

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: istio-system
spec:
  host: frontend
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: DISABLE