pipeline {

  options {
    ansiColor('xterm')
  }

  agent {
    kubernetes {
      yamlFile 'builder.yaml'
    }
  }

  stages {

    stage('Kaniko Build & Push "checkoutservice" Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/src/checkoutservice/Dockerfile \
                             --context `pwd`/src/checkoutservice/ \
                             --destination=marinyuk/checkoutservice:${BUILD_NUMBER} \
                             --destination=marinyuk/checkoutservice:latest
            '''
          }
        }
      }
    }

    stage('Deploy "checkoutservice" App to Kubernetes') {     
      steps {
        container('kubectl') {
          withCredentials([file(credentialsId: 'mykubeconfig', variable: 'KUBECONFIG')]) {
            sh 'sed -i "s/latest/${BUILD_NUMBER}/" /src/checkoutservice/yaml/deployment.yaml'
            sh 'kubectl apply -f /src/checkoutservice/yaml/deployment.yaml -n microservices'
          }
        }
      }
    }
  
  }
}