pipeline {

  options {
    ansiColor('xterm')
  }

  agent {
    kubernetes {
      yamlFile 'builder.yaml'
    }
  }

  stages {

    stage('Kaniko Build & Push "emailservice" Image') {
      steps {
        container('kaniko') {
          script {
            sh '''
            /kaniko/executor --dockerfile `pwd`/src/emailservice/Dockerfile \
                             --context `pwd`/src/emailservice/ \
                             --destination=marinyuk/emailservice:${BUILD_NUMBER} \
                             --destination=marinyuk/emailservice:latest
            '''
          }
        }
      }
    }

    stage('Deploy "emailservice" App to Kubernetes') {     
      steps {
        container('kubectl') {
          withCredentials([file(credentialsId: 'mykubeconfig', variable: 'KUBECONFIG')]) {
            sh 'sed -i "s/latest/${BUILD_NUMBER}/" src/emailservice/yaml/deployment.yaml'
            sh 'cat src/emailservice/yaml/deployment.yaml'
            sh 'kubectl apply -f src/emailservice/yaml/deployment.yaml -n microservices'
          }
        }
      }
    }
  
  }
}